TEL_CHIP := -DCHIP_TYPE=CHIP_TYPE_8258
LIBS :=  -llt_8258
TEL_PATH := ..

PROJECT_NAME := HanshowESL
DOWNLOAD_PORT := /dev/ttyUSB0

PROJECT_PATH := .

OUT_PATH :=$(TEL_PATH)/out

#include the SDK makefile
-include $(TEL_PATH)/make/makefile